# Generated by Django 4.1.3 on 2023-02-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absent_emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Name', models.CharField(max_length=200)),
                ('Emp_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(max_length=200)),
                ('Designation', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'absent_emp',
            },
        ),
        migrations.CreateModel(
            name='Addemployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Contact', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('D_O_B', models.DateField(blank=True, null=True)),
                ('Date_of_join', models.DateField(blank=True, null=True)),
                ('department', models.CharField(max_length=200)),
                ('Designation', models.CharField(max_length=200)),
                ('Reporting_Dept', models.CharField(max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('User_name', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Confirm_Password', models.CharField(max_length=200)),
                ('Emp_ID', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='images/')),
                ('Emp_status', models.IntegerField(blank=True, default=0, null=True)),
                ('Total_Paid_Leave', models.CharField(blank=True, default='15', max_length=10, null=True)),
                ('Total_Sick_Leave', models.CharField(blank=True, default='15', max_length=10, null=True)),
                ('Total_HalfDay_Leave', models.CharField(blank=True, default='15', max_length=10, null=True)),
                ('Total_Unpaid_Leave', models.CharField(blank=True, default='15', max_length=10, null=True)),
                ('Pending_Paid_Leave', models.CharField(blank=True, default='15', max_length=10, null=True)),
                ('Pending_Sick_Leave', models.CharField(blank=True, default='15', max_length=10, null=True)),
                ('Pending_HalfDay_Leave', models.CharField(blank=True, default='15', max_length=10, null=True)),
                ('Pending_Unpaid_Leave', models.CharField(blank=True, default='15', max_length=10, null=True)),
            ],
            options={
                'db_table': 'add_employee',
            },
        ),
        migrations.CreateModel(
            name='Admin_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'admin_Login',
            },
        ),
        migrations.CreateModel(
            name='CompanySetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, unique=True)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('telephone', models.CharField(blank=True, max_length=500, null=True)),
                ('telephone1', models.CharField(blank=True, max_length=500, null=True)),
                ('telephone2', models.CharField(blank=True, max_length=500, null=True)),
                ('Address', models.CharField(blank=True, max_length=500, null=True)),
                ('zip', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=500, null=True)),
                ('companyBranch', models.CharField(blank=True, max_length=500, null=True)),
                ('department1', models.CharField(blank=True, max_length=500, null=True)),
                ('department2', models.CharField(blank=True, max_length=500, null=True)),
                ('department3', models.CharField(blank=True, max_length=500, null=True)),
                ('department4', models.CharField(blank=True, max_length=500, null=True)),
                ('department5', models.CharField(blank=True, max_length=500, null=True)),
                ('company_status', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'company_setup',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Birthday', 'Birthday'), ('Public Holiday', 'Public Holiday'), ('Event', 'Event')], max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Leave_App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Category', models.CharField(blank=True, max_length=200, null=True)),
                ('From', models.CharField(blank=True, max_length=200, null=True)),
                ('to', models.CharField(blank=True, max_length=200, null=True)),
                ('leavedayCategory_From', models.CharField(blank=True, max_length=200, null=True)),
                ('leavedayCategory_to', models.CharField(blank=True, max_length=200, null=True)),
                ('Reason', models.CharField(blank=True, max_length=250, null=True)),
                ('Emp_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('Leave_count_Category', models.CharField(blank=True, max_length=2, null=True)),
                ('leave_status', models.IntegerField(blank=True, default=0, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('Designation', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('Absentemp_status', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'leave',
            },
        ),
        migrations.CreateModel(
            name='Leave_Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=20, null=True)),
                ('leavepolicy', models.CharField(max_length=50000)),
                ('leave_status', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'leavepolicy',
            },
        ),
    ]
