# Generated by Django 4.1.7 on 2023-03-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotes', models.CharField(max_length=100)),
                ('tod_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'quote',
            },
        ),  
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Public Holiday', 'Public Holiday'), ('Event', 'Event'), ('Others', 'Others')], max_length=20),
        ),
    ]
